export interface Country {
  code: string;
  nameAr: string;
  nameEn: string;
  dialCode: string;
  flag: string;
  placeholder: string;
  maxLength: number;
}

export const COUNTRIES: Country[] = [
  {
    code: "YE",
    nameAr: "اليمن",
    nameEn: "Yemen",
    dialCode: "+967",
    flag: "🇾🇪",
    placeholder: "71 234 5678",
    maxLength: 9,
  },
  {
    code: "SA",
    nameAr: "المملكة العربية السعودية",
    nameEn: "Saudi Arabia",
    dialCode: "+966",
    flag: "🇸🇦",
    placeholder: "50 123 4567",
    maxLength: 9,
  },
  {
    code: "AE",
    nameAr: "الإمارات العربية المتحدة",
    nameEn: "United Arab Emirates",
    dialCode: "+971",
    flag: "🇦🇪",
    placeholder: "50 123 4567",
    maxLength: 9,
  },
  {
    code: "KW",
    nameAr: "الكويت",
    nameEn: "Kuwait",
    dialCode: "+965",
    flag: "🇰🇼",
    placeholder: "9123 4567",
    maxLength: 8,
  },
  {
    code: "QA",
    nameAr: "قطر",
    nameEn: "Qatar",
    dialCode: "+974",
    flag: "🇶🇦",
    placeholder: "3123 4567",
    maxLength: 8,
  },
  {
    code: "BH",
    nameAr: "البحرين",
    nameEn: "Bahrain",
    dialCode: "+973",
    flag: "🇧🇭",
    placeholder: "3123 4567",
    maxLength: 8,
  },
  {
    code: "OM",
    nameAr: "عُمان",
    nameEn: "Oman",
    dialCode: "+968",
    flag: "🇴🇲",
    placeholder: "9123 4567",
    maxLength: 8,
  },
  {
    code: "EG",
    nameAr: "مصر",
    nameEn: "Egypt",
    dialCode: "+20",
    flag: "🇪🇬",
    placeholder: "10 1234 5678",
    maxLength: 10,
  },
  {
    code: "JO",
    nameAr: "الأردن",
    nameEn: "Jordan",
    dialCode: "+962",
    flag: "🇯🇴",
    placeholder: "7 9123 4567",
    maxLength: 9,
  },
  {
    code: "IQ",
    nameAr: "العراق",
    nameEn: "Iraq",
    dialCode: "+964",
    flag: "🇮🇶",
    placeholder: "770 123 4567",
    maxLength: 10,
  },
  {
    code: "LB",
    nameAr: "لبنان",
    nameEn: "Lebanon",
    dialCode: "+961",
    flag: "🇱🇧",
    placeholder: "71 123 456",
    maxLength: 8,
  },
  {
    code: "SY",
    nameAr: "سوريا",
    nameEn: "Syria",
    dialCode: "+963",
    flag: "🇸🇾",
    placeholder: "91 234 5678",
    maxLength: 9,
  },
  {
    code: "PS",
    nameAr: "فلسطين",
    nameEn: "Palestine",
    dialCode: "+970",
    flag: "🇵🇸",
    placeholder: "59 123 4567",
    maxLength: 9,
  },
  {
    code: "SD",
    nameAr: "السودان",
    nameEn: "Sudan",
    dialCode: "+249",
    flag: "🇸🇩",
    placeholder: "91 234 5678",
    maxLength: 9,
  },
  {
    code: "MA",
    nameAr: "المغرب",
    nameEn: "Morocco",
    dialCode: "+212",
    flag: "🇲🇦",
    placeholder: "61 234 5678",
    maxLength: 9,
  },
  {
    code: "DZ",
    nameAr: "الجزائر",
    nameEn: "Algeria",
    dialCode: "+213",
    flag: "🇩🇿",
    placeholder: "55 123 4567",
    maxLength: 9,
  },
  {
    code: "TN",
    nameAr: "تونس",
    nameEn: "Tunisia",
    dialCode: "+216",
    flag: "🇹🇳",
    placeholder: "20 123 456",
    maxLength: 8,
  },
  {
    code: "LY",
    nameAr: "ليبيا",
    nameEn: "Libya",
    dialCode: "+218",
    flag: "🇱🇾",
    placeholder: "91 123 4567",
    maxLength: 9,
  },
  {
    code: "TR",
    nameAr: "تركيا",
    nameEn: "Turkey",
    dialCode: "+90",
    flag: "🇹🇷",
    placeholder: "501 234 5678",
    maxLength: 10,
  },
  {
    code: "US",
    nameAr: "الولايات المتحدة",
    nameEn: "United States",
    dialCode: "+1",
    flag: "🇺🇸",
    placeholder: "202 555 0123",
    maxLength: 10,
  },
  {
    code: "GB",
    nameAr: "المملكة المتحدة",
    nameEn: "United Kingdom",
    dialCode: "+44",
    flag: "🇬🇧",
    placeholder: "7911 123456",
    maxLength: 10,
  },
];

export const DEFAULT_COUNTRY = COUNTRIES[0]; // اليمن كافتراضي أو أول دولة
